version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: broadcast-derby
    volumes:
      - ./web/:/usr/src/web
      - /mnt/c/CommentGenerator/Multi/CommentGenerator0.0.8a:/usr/src/web/public/setting
    ports:
      - 9870:9870
    tty: true
