name: release

on:
  push:
    branches:
    - main

jobs:
  build-deploy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: '16.6'

    - name: install
      run: cd ./web && npm install

    - name: build
      run: cd ./web && npm run build
    
    - name: get-npm-version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@master

    - name: echo-npm-version
      id: echo-version
      run: |
        echo v${{ steps.package-version.outputs.current-version}}

    - name: Create a release pull request
      uses: bakunyo/git-pr-release-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_PR_RELEASE_BRANCH_PRODUCTION: release
        GIT_PR_RELEASE_BRANCH_STAGING: main
        GIT_PR_RELEASE_LABELS: release
        NPM_VERSION: v${{ steps.package-version.outputs.current-version}}
        GIT_PR_RELEASE_TEMPLATE: .git-pr-release-template